name = "NavierStokes"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["NavierStokes"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
git = "https://github.com/alejandro-soto-franco/mathlib4"
rev = "698d2b68b870f1712040ab0c233d34372d4b56df"

[[lean_lib]]
name = "NavierStokes"
